CREATE TABLE IF NOT EXISTS chuleta (
  tema_id INTEGER PRIMARY KEY REFERENCES temas(id) ON DELETE CASCADE,
  markdown TEXT NOT NULL CHECK (length(markdown) > 0),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mapa (
  tema_id INTEGER PRIMARY KEY REFERENCES temas(id) ON DELETE CASCADE,
  mermaid TEXT NOT NULL CHECK (length(mermaid) > 0),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
